- hosts: localhost
  become: yes
  gather_facts: false
  tasks:  
  - name: Update apt packages
    remote_user: root
    apt:
      update_cache: yes
  - name: Install nginx
    apt:
      name: nginx
      state: latest
  - name: start nginx service
    service:
      name: nginx
      state: started
